### ISSUE TITLE
Segmentation Falut - Failed to find video/ audio codec

### ISSUE THREAD

**Issue by oomek** [ximonsson/rpi-mediaplayer#1]
Hi, I tried your player, but it does not recognise the codecs. Do you have any clue what might be causing it?

```pi@retropie:~/dev/rpimp/bin $ ./player test.mp4
Failed to find video codec
Failed to find audio codec
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 512
    compatible_brands: mp42
    creation_time   : 2018-12-22T10:48:14.000000Z
    media_type      : 9
    season_number   : 0
    episode_sort    : 0
    hd_video        : 0
    iTunMOVI        : <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"  "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict><key>studio</key><string>studio</string><key>cast</key><array><dict><key>name<
  Duration: 00:01:00.10, start: 0.000000, bitrate: 2159 kb/s
    Stream #0:0(eng): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 854x480 [SAR 1:1 DAR 427:240], 2025 kb/s, 30 fps, 30 tbr, 90k tbn, 60 tbc (default)
    Metadata:
      creation_time   : 2018-12-22T10:48:14.000000Z
      handler_name    : VideoHandler
      encoder         : h264
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 126 kb/s (default)
    Metadata:
      creation_time   : 2018-12-22T10:48:14.000000Z
      handler_name    : SoundHandler
>> Segmentation fault
```

**Comment by oomek** [comment]
Nevermind, it was a ffmpeg version mismatch. The last working ffmpeg version with the player is 3.4.5

**Comment by ximonsson** [comment]
Thank you for pointing it out!

I haven't worked on this project for some time, but now I know it would be good to update it to work with latest fffmpeg version when the time comes.

**Comment by oomek** [comment]
You're welcome. I've been trying recently to add OpenMAX decoder to the project I'm contributing to, but I was getting weird glitching, synchronisation issues, then I found your work. How much effort you think it would require to squash those deallocation bugs and memory leaks? Oh and another one if I may: in tunelled/texture mode there is tearing visible on low resolution videos. Is there any form of synchronisation that can be added to tell the VC to not to update the texture while the texture is being drawn on the screen?

**Comment by ximonsson** [comment]
How low is low resolution in this case? Not sure what resolutions I have tried myself, but it is true that I mainly focused on HD videos to make sure performance was good enough, but SD videos I have most likely tried as well. 

It was quite tricky to get everything timed well enough when rendering to a texture, with updates maybe things are not working as well as before because I am pretty sure I was able to solve the timing issue. At least kind of, if I remember correctly I tried to mutex the image it renders to so it would not be updated while drawn. I actually only noticed that kind of error with high resolution videos because then the drawing and update processes are much slower. Another way of solving (and probably much more correct) would be to have two images: one your render to, then copy to another one that is drawn. 

The provided example for rendering on a texture did not either show how to properly deallocate the tunnels that you create and I had to try to figure that out by myself, but without success as you have seen. I am guessing that I am sending the signals in the wrong order or similar. I have not spent so much time on that particular problem, but I would think it is not so much work as soon as you can find the proper way to do it.

Did you find any memory leaks besides that? In that case I am probably not aware of them. I am sure I have run the player on long HD videos and there has been no problem, but I have not done any extensive testing.

I got a little in the mood now to dig out my Raspberry and test this again. Maybe I have some time during the week to checkout the code again and see how things are performing.

**Comment by oomek** [comment]
Attract Mode launcher that I was hoping to implement your player into is reloading videos very aggressively, thus even slight unallocated memory might be problematic. 
I did testing again for tearing  with the following streams:
```
1080p60 - ( just for giggles )
1080p30 - T
720p60  - T
720p30  - OK
480p60  - occasional tearing on top
480p30  - OK
360p60  - T
360p30  - OK
240p60  - OK
240p30  - OK
224p60  - OK
224p30  - OK
```
Interleaving EGLImages is what I was also thinking about, but can it be bound in the callback on each frame without hurting the performance? Also since the buffer usually contain more than one frame is it even doable?

I'm attaching the test patterns I was using for your convenience.
[moving_bar.zip](https://github.com/ximonsson/rpi-mediaplayer/files/3003516/moving_bar.zip)

**Comment by oomek** [comment]
I'm assuming the tearing pattern may be different if your player is not only one that queues OpenGL drawing, so flip-flopping EGLImages seems like the best way to go.

**Comment by oomek** [comment]
Native OpenMAX decoding got me so excited as the current MMAL implementation in Attract Mode has dreadful performance ( sws_scale + copying the texture 3 times between CPU-GPU ) Any input from you would be invaluable as you seem to know a lot in that matter. I only started digging in the OMIL 2 weeks ago and my head is on a verge of exploding. I've never seen such non user friendly api ever in my life :D

**Comment by ximonsson** [comment]
Is this project your are contributing to http://attractmode.org/about.html ?

Regarding interleaved frames there might be a way to get FFmpeg to decode to a single AVFrame the both interleaved ones. But I might be wrong. I used to work with a system that played interleaved recorded material and then we had to manually interleave the decoded frames. It's not a big deal but it would be a pain to implement this to my work here I think. I can find lots of design flaws in it (that might get fixed some day).

I think a good first step would be to implement flipping of EGLImages to remove tearing. Even though I am a little surprised that there are any at all considering the mutex. 

I completly understand the struggling with the OpenMax IL components documentation. At least when I was trying it out it was not super well documented and it was quite spread out. But when you understand the concept of their tunnels and how you link components through their input and output ports you kind of get a hang of it. But there are a lot of crazy stuff that you need to stumble upon to figure out .... 

I am guessing you have already found these links for docs:
http://www.jvcref.com/files/PI/documentation/ilcomponents/
http://maemo.org/api_refs/5.0/beta/libomxil-bellagio/annotated.html
https://github.com/raspberrypi/firmware/tree/master/hardfp/opt/vc/src/hello_pi (hello_video and hello_videocube examples)

**Comment by oomek** [comment]
Yes, that's the one:
http://github.com/mickelson/attract

I'm not sure if I worded my thoughts properly.To clarify: By interleaving I meant (flip-flopping) seting the tunnel output to different eglimage on each frame, I wasn't reffering to interlaced source. Thanks for the links. I haven't seen the first one.

**Comment by ximonsson** [comment]
Oh cool project. I had an idea for a similar project ones, but never got that far with it =P. Are you working with rendering some videos in interface?

Ok now I understand what you meant by interleaving. From what I know you can not change the structure of the tunnels once they are made. I remember that I had some videos that had audio streams that changed all of a sudden, going from stereo sound to 5.1. I found that the omxplayer solves this by constantly checking if the sound parameters have changed and in that case they destroy the audio tunnel and then rebuild it. With that in mind I would guess that you can not change the destination image dynamically either. 

I checked my code and it does not either look like you could use a pointer to pointer solution there. But I must admit that I do not remember all the magic involved in getting it to work. Lines 152-162 is the callback that OpenMAX calls when a new frame has been rendered. I guess there is where to update in making a copy of the image. Spontanously I would say that there should be some method that copies textures quite fast on the GPU.

**Comment by oomek** [comment]
Attract Mode is a frontend for emulation that gives the ability to construct themes ( called layouts ) that are written in simplistic language called Squirrel, it can show snapshots and videos captured from emulators.

I'm currently fixing bugs and improving overall performance, then I'm planning to add more features from my ToDo list as I did before. I bought RPI just for debugging purposes and I was shocked how badly AM runs on the Raspberry. RPI has a potential when handled natively, that's my current goal.

I've tried calling OMX_UseEGLImage inside the callback, and indeed it's destroying the tunnel, that's very unfortunate.

Can you be contacted over the email or discord, facebook etc to not pollute this issue anymore?

**Comment by ximonsson** [comment]
Ah yes, I didn't realize we got a little off-topic here. Feel free to send an email, my contact info should be in my profile =)

**Comment by oomek** [comment]
It seems that adding a small delay to timestamps ( 3 frames ) solves tearing in lower resolution streams
https://github.com/ximonsson/rpi-mediaplayer/blob/4d54347b3c7e4ff61025a23971974b0458d0a894/src/player.c#L171
after this line add:
```
ticks.nLowPart += 16666 * 3;
```
Something to do with double/triple buffering? Frames are rendered in advance so maybe my addition just compensates for it. It even fixed that slight lipsync delay with analog audio :)
This video https://www.youtube.com/watch?v=ucZl6vQ_8Uo (720p30) when downloaded is now perfectly in sync.
Not sure if it can stay constant, or it should be tied to time_base or refresh rate.  The resolutions 1080p60, 1080p30 and 720p60 are the ones that still tear.

p.s. Did you get my emails?

**Comment by oomek** [comment]
Hi, I found the cause of freezing in texture mode. There is no wait call in your code that would block destroying tunnels until egl_render receives EOS. I've tried several options but nothing seems to work. Any clues?


________________________________
